apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitalstream-query
  namespace: vitalstream
  labels:
    app: vitalstream-query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vitalstream-query
  template:
    metadata:
      labels:
        app: vitalstream-query
      annotations:
        # Tells Prometheus to scrape /metrics on port 8080
        prometheus.io/scrape: "true"
        prometheus.io/path:   "/metrics"
        prometheus.io/port:   "8080"
    spec:
      containers:
        - name: query
          image: vitalstream.query:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: clinical-thresholds
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: Redis__ConnectionString
              value: "redis:6379"
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: vitalstream-query
  namespace: vitalstream
spec:
  selector:
    app: vitalstream-query
  ports:
    - port: 80
      targetPort: 8080